version: '3.8'
services:
  product:
    build: microservices/product-service
    environment:
      - spring.profiles.active=docker,streaming_partitioned,streaming_instance_0
    deploy:
      resources:
        reservations:
          memory: 512m
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  product-1:
    build: microservices/product-service
    environment:
      - spring.profiles.active=docker,streaming_partitioned,streaming_instance_1
    deploy:
      resources:
        reservations:
          memory: 512m
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  recommendation:
    build: microservices/recommendation-service
    environment:
      - spring.profiles.active=docker,streaming_partitioned,streaming_instance_0
    deploy:
      resources:
        reservations:
          memory: 512m
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  recommendation-1:
    build: microservices/recommendation-service
    environment:
      - spring.profiles.active=docker,streaming_partitioned,streaming_instance_1
    deploy:
      resources:
        reservations:
          memory: 512m
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  review:
    build: microservices/review-service
    environment:
      - spring.profiles.active=docker,streaming_partitioned,streaming_instance_0
    deploy:
      resources:
        reservations:
          memory: 512m
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  review-1:
    build: microservices/review-service
    environment:
      - spring.profiles.active=docker,streaming_partitioned,streaming_instance_1
    deploy:
      resources:
        reservations:
          memory: 512m
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  product-composite:
    build: microservices/product-composite-service
    environment:
      - spring.profiles.active=docker,streaming_partitioned
    deploy:
      resources:
        reservations:
          memory: 512m

  mongodb:
    image: mongo:7.0.2
    ports:
      - "27017:27017"
    deploy:
      resources:
        reservations:
          memory: 512m
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 2s
      retries: 60

  mysql:
    image: mysql:8.0.35
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=review-db
      - MYSQL_PASSWORD=root
    deploy:
      resources:
        reservations:
          memory: 512m
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60

  rabbitmq:
    image: rabbitmq:3.12.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        reservations:
          memory: 512m
    healthcheck:
      test: ["CMD","rabbitmqctl","status"]
      interval: 5s
      timeout: 2s
      retries: 60

  eureka:
    build: spring-cloud/eureka-server
    deploy:
      resources:
        reservations:
          memory: 512m

  gateway:
    build: spring-cloud/gateway
    environment:
      - spring.profiles.active=docker
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          memory: 512m