version: '3.8'
services:
  product:
    build: microservices/product-service
    image: krishnaramachandran1973/product-service:v2
    environment:
      - spring.profiles.active=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_USERNAME=${CONFIG_SERVER_USR}
      - SPRING_CLOUD_CONFIG_PASSWORD=${CONFIG_SERVER_PWD}
    deploy:
      resources:
        reservations:
          memory: 512m
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  recommendation:
    build: microservices/recommendation-service
    image: krishnaramachandran1973/recommendation-service:v2
    environment:
      - spring.profiles.active=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_USERNAME=${CONFIG_SERVER_USR}
      - SPRING_CLOUD_CONFIG_PASSWORD=${CONFIG_SERVER_PWD}
    deploy:
      resources:
        reservations:
          memory: 512m
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  review:
    build: microservices/review-service
    image: krishnaramachandran1973/review-service:v2
    environment:
      - spring.profiles.active=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_USERNAME=${CONFIG_SERVER_USR}
      - SPRING_CLOUD_CONFIG_PASSWORD=${CONFIG_SERVER_PWD}
    deploy:
      resources:
        reservations:
          memory: 512m
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  product-composite:
    build: microservices/product-composite-service
    image: krishnaramachandran1973/product-composite-service
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_USERNAME=${CONFIG_SERVER_USR}
      - SPRING_CLOUD_CONFIG_PASSWORD=${CONFIG_SERVER_PWD}
    deploy:
      resources:
        reservations:
          memory: 512m
    depends_on:
      rabbitmq:
        condition: service_healthy
      auth-server:
        condition: service_healthy

  mongodb:
    image: mongo:7.0.2
    ports:
      - "27017:27017"
    deploy:
      resources:
        reservations:
          memory: 512m
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 2s
      retries: 60

  mysql:
    image: mysql:8.0.35
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=review-db
      - MYSQL_PASSWORD=root
    deploy:
      resources:
        reservations:
          memory: 512m
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60

  rabbitmq:
    image: rabbitmq:3.12.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        reservations:
          memory: 512m
    healthcheck:
      test: ["CMD","rabbitmqctl","status"]
      interval: 5s
      timeout: 2s
      retries: 60

  auth-server:
    build: spring-cloud/authorization-server
    image: krishnaramachandran1973/auth-server
    environment:
      - spring.profiles.active=default
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_USERNAME=${CONFIG_SERVER_USR}
      - SPRING_CLOUD_CONFIG_PASSWORD=${CONFIG_SERVER_PWD}
    deploy:
      resources:
        reservations:
          memory: 512m
    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://localhost:9999/actuator/health" ]
      interval: 5s
      timeout: 2s
      retries: 60