version: '3.8'
services:
  product:
    build: microservices/product-service
    environment:
      - spring.profiles.active=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_USERNAME=${CONFIG_SERVER_USR}
      - SPRING_CLOUD_CONFIG_PASSWORD=${CONFIG_SERVER_PWD}
    deploy:
      resources:
        reservations:
          memory: 512m
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  recommendation:
    build: microservices/recommendation-service
    environment:
      - spring.profiles.active=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_USERNAME=${CONFIG_SERVER_USR}
      - SPRING_CLOUD_CONFIG_PASSWORD=${CONFIG_SERVER_PWD}
    deploy:
      resources:
        reservations:
          memory: 512m
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  review:
    build: microservices/review-service
    environment:
      - spring.profiles.active=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_USERNAME=${CONFIG_SERVER_USR}
      - SPRING_CLOUD_CONFIG_PASSWORD=${CONFIG_SERVER_PWD}
    deploy:
      resources:
        reservations:
          memory: 512m
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  product-composite:
    build: microservices/product-composite-service
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_USERNAME=${CONFIG_SERVER_USR}
      - SPRING_CLOUD_CONFIG_PASSWORD=${CONFIG_SERVER_PWD}
    deploy:
      resources:
        reservations:
          memory: 512m
    depends_on:
      rabbitmq:
        condition: service_healthy
      auth-server:
        condition: service_healthy

  mongodb:
    image: mongo:7.0.2
    ports:
      - "27017:27017"
    deploy:
      resources:
        reservations:
          memory: 512m
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 2s
      retries: 60

  mysql:
    image: mysql:8.0.35
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=review-db
      - MYSQL_PASSWORD=root
    deploy:
      resources:
        reservations:
          memory: 512m
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60

  rabbitmq:
    image: rabbitmq:3.12.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        reservations:
          memory: 512m
    healthcheck:
      test: ["CMD","rabbitmqctl","status"]
      interval: 5s
      timeout: 2s
      retries: 60

  eureka:
    build: spring-cloud/eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_USERNAME=${CONFIG_SERVER_USR}
      - SPRING_CLOUD_CONFIG_PASSWORD=${CONFIG_SERVER_PWD}
    deploy:
       resources:
         reservations:
           memory: 512m

  gateway:
    build: spring-cloud/gateway
    environment:
      - spring.profiles.active=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_USERNAME=${CONFIG_SERVER_USR}
      - SPRING_CLOUD_CONFIG_PASSWORD=${CONFIG_SERVER_PWD}
    ports:
      - "8443:8443"
    deploy:
      resources:
        reservations:
          memory: 512m
    depends_on:
      eureka:
        condition: service_started
      auth-server:
        condition: service_healthy

  auth-server:
    build: spring-cloud/authorization-server
    environment:
      - spring.profiles.active=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_CLOUD_CONFIG_USERNAME=${CONFIG_SERVER_USR}
      - SPRING_CLOUD_CONFIG_PASSWORD=${CONFIG_SERVER_PWD}
    deploy:
      resources:
        reservations:
          memory: 512m
    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://localhost:9999/actuator/health" ]
      interval: 5s
      timeout: 2s
      retries: 60
    depends_on:
      eureka:
        condition: service_started

  config-server:
    build: spring-cloud/config-server
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          memory: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker,native
      - ENCRYPT_KEY=${CONFIG_SERVER_ENCRYPT_KEY}
      - SPRING_SECURITY_USER_NAME=${CONFIG_SERVER_USR}
      - SPRING_SECURITY_USER_PASSWORD=${CONFIG_SERVER_PWD}
    volumes:
      - $PWD/config-repo:/config-repo

  zipkin-server:
    image: openzipkin/zipkin:latest
    restart: always
    deploy:
      resources:
        reservations:
          memory: 1024m
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"