deployment:
  name: gateway
  label: gateway

  container:
    image: krishnaramachandran1973/gateway
    tag: latest
    port: 8443
    spring_profile: SPRING_PROFILES_ACTIVE
    spring_profile_value: docker
    config_location: file:/config-repo/application.properties,file:/config-repo/application-docker.properties,file:/config-repo/gateway.properties
    livenessProbe_url: /actuator/health/liveness
    readinessProbe_url: /actuator/health/readiness

  service:
    name: gateway
    type: NodePort
    selector: gateway
    port: 443
