deployment:
  name: config-server
  label: config-server

  container:
    image: krishnaramachandran1973/config-server
    tag: latest
    port: 8888
    spring_profile: SPRING_PROFILES_ACTIVE
    spring_profile_value: docker, native
    livenessProbe_url: /actuator/health/liveness
    readinessProbe_url: /actuator/health/readiness

  service:
    name: config-server
    type: ClusterIP
    selector: config-server
    port: 80
