apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.label }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Values.deployment.label }}
    spec:
      containers:
        - name: {{.Values.deployment.label}}
          image: {{.Values.deployment.container.image}}:{{.Values.deployment.container.tag}}
          imagePullPolicy: IfNotPresent
          env:
            - name: {{.Values.deployment.container.spring_profile}}
              value: {{.Values.deployment.container.spring_profile_value}}
            - name: SPRING_CLOUD_CONFIG_URI
              value: {{.Values.deployment.container.cloud_config_uri_value}}
            - name: SPRING_CLOUD_CONFIG_USERNAME
              value: dev-user  
            - name: SPRING_CLOUD_CONFIG_PASSWORD
              value: dev-pwd   
          ports:
            - containerPort: {{.Values.deployment.container.port}}
          livenessProbe:
            httpGet:
              path: {{.Values.deployment.container.livenessProbe_url}}
              port: {{.Values.deployment.container.port}}
              scheme: HTTPS
            initialDelaySeconds: 25
            periodSeconds: 15  
          readinessProbe:
            httpGet:
              path: {{.Values.deployment.container.readinessProbe_url}}
              port: {{.Values.deployment.container.port}}
              scheme: HTTPS
            initialDelaySeconds: 25
            periodSeconds: 15    
          resources:
            limits:
              cpu: '500m'
              memory: '1024Mi'
